#!/usr/bin/env bash
source "lib/ac-bash-preamble" || exit 1

target_dirname="${PWD}"
link_dirname="${HOME}"

while read target_link ; do

  read -ra target_link <<< "${target_link}"
  echo $target_link

  target_basename="${target_link[0]}"
  if [[ ${#target_link[@]} == 1 ]] ; then
    link_basename="${target_basename}"
  elif [[ ${#target_link[@]} == 2 ]] ; then
    link_basename="${target_link[1]}"
  else
    exit 1
  fi

  target="${target_dirname}/${target_basename}"
  link_name="${link_dirname}/${link_basename}"

  echo "Installing ${target}..."
  if [[ -L ${link_name} ]]
  then
    existing_target="$(readlink ${link_name})"
    if [[ "${existing_target}" == ${target} ]]
    then
      echo "${target} already installed"
    else
      echo "${link_name} already linked to ${existing_target}"
      read -p "Would you like to replace this link? (y/n): " -n 1
      echo
      if [[ $REPLY =~ ^[Yy]$ ]]
      then
        unlink "${link_name}"
        ln --symbolic -T "${target}" "${link_name}" || echo "Link not created"
      fi
    fi
  elif [[ -f ${link_name} || -d ${link_name} ]]
  then
    echo "A file/directory with name ${link_name} already exists"
    read -p "Would you like to backup and replace it? (y/n): " -n 1
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      mv "${link_name}" "${link_name}.bak"
      ln --symbolic -T "${target}" "${link_name}" || echo "Link not created"
    fi
  else
    mkdir --parents "$(dirname ${link_name})"
    ln --symbolic -T "${target}" "${link_name}" || echo "Link not created"
  fi
done < "install_list.csv"

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

# Make sure permissions are correct
chmod 700 .ssh
chmod 600 .ssh/*
