#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

ac_exit_commands=()
ac-trap-function() {
    if [[ "${#ac_exit_commands[@]}" != 0 ]] ; then
        local com
	local i
	for ((i=${#ac_exit_commands[@]}-1;i>=0;i--)) ; do
            # echo "Running exit command:"
	    # echo "${ac_exit_commands[$i]}"
	    eval "${ac_exit_commands[$i]}"
        done
    fi
}
trap ac-trap-function EXIT
ac-exit-push() {
    ac_exit_commands[${#ac_exit_commands[@]}]="${1}"
}
ac-exit-flush() {
    ac-trap-function
    ac_exit_commands=()
}

dlock() {
    local dirname="${1}"
    shift
    while ! mkdir "${dirname}" 2>/dev/null ; do : ; done
    local pidfile="${dirname}/pid"
    # echo $$
    # echo $$ > "${pidfile}"
    # ac-exit-push "if [[ -f '${pidfile}' && x$(head -n 1 '${pidfile}') == x$$ ]] ; then rm -rf '${dirname}' ; fi"
    "$@"
    rm -rf "${dirname}"
}
